# Site settings
title: MIA Sprint 2 
email: fake@fake.com
description: > # this means to ignore newlines until "baseurl:"
	MIA second sprint plan.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
gems: [jekyll-relative]

# Build settings
markdown: kramdown
